<?php

namespace RestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use RestBundle\Entity\Message;
use RestBundle\Entity\User;

/**
 * MessageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getUserMessages(User $user)
    {
        return $this->createQueryBuilder('message')
            ->where('message.owner = :user')
            ->orderBy('message.id', 'ASC')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getResult();
    }
 

    /**
     * @return Message[]|array
     */
    public function getUnreadMessages()
    {
        // for sending mails
        $date = (new \DateTime())->modify('-2 minutes');

        return $this->createQueryBuilder('message')
            ->join('message.unread_users as u')
            ->where('u.id > 0')
            ->andWhere('message.date < :date')
            ->orderBy('message.id', 'ASC')
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult();
    }
}
